version: "2"
linters:
  default: none
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Extra
    - asciicheck
    - bodyclose
    - gocheckcompilerdirectives
    - noctx
    - perfsprint
    - prealloc
    - unconvert
    - testifylint

  settings:
    errcheck:
      verbose: true
      exclude-functions:
        # Things commonly used in a defer statement
        - (*database/sql.Rows).Close
        - (*database/sql.Tx).Rollback
        - (*github.com/minio/minio-go/v7.Object).Close
        - (*compress/gzip.Reader).Close
        - (*os.File).Close
        - (io.Closer).Close

    govet:
      enable:
        - nilness
